#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 24 16:41:10 EST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tester_sprites_display_behav -key {Behavioral:sim_2:Functional:tester_sprites_display} -tclbatch tester_sprites_display.tcl -log simulate.log"
xsim tester_sprites_display_behav -key {Behavioral:sim_2:Functional:tester_sprites_display} -tclbatch tester_sprites_display.tcl -log simulate.log

